export const a1WordLists = [
  { id: "a1-countries", title: "A1 • Ülkeler ve Milliyetler", accent: "violet", words: [
    {"english": "Brazil", "pronunciation": "brızil", "turkish": "Brezilya"},
    {"english": "Brazilian", "pronunciation": "brızilyın", "turkish": "Brezilyalı"},
    {"english": "France", "pronunciation": "frans", "turkish": "Fransa"},
    {"english": "French", "pronunciation": "frenç", "turkish": "Fransız; Fransızca"},
    {"english": "German", "pronunciation": "cörmın", "turkish": "Alman; Almanca"},
    {"english": "Germany", "pronunciation": "cörmıni", "turkish": "Almanya"},
    {"english": "Japan", "pronunciation": "cıpen", "turkish": "Japonya"},
    {"english": "Japanese", "pronunciation": "cepıniiz", "turkish": "Japon; Japonca"},
    {"english": "Spain", "pronunciation": "speyn", "turkish": "İspanya"},
    {"english": "Spanish", "pronunciation": "speniş", "turkish": "İspanyol; İspanyolca"},
    {"english": "American", "pronunciation": "ımerikın", "turkish": "Amerikalı"},
    {"english": "Argentina", "pronunciation": "aacıntiinı", "turkish": "Arjantin"},
    {"english": "Australia", "pronunciation": "ostreyliı", "turkish": "Avustralya"},
    {"english": "Britain", "pronunciation": "britın", "turkish": "Britanya"},
    {"english": "British", "pronunciation": "britiş", "turkish": "Britanyalı"},
    {"english": "Canada", "pronunciation": "kenıdı", "turkish": "Kanada"},
    {"english": "Canadian", "pronunciation": "kıneydiın", "turkish": "Kanadalı"},
    {"english": "China", "pronunciation": "çaynı", "turkish": "Çin"},
    {"english": "Chinese", "pronunciation": "çayniiz", "turkish": "Çinli; Çince"},
    {"english": "Colombia", "pronunciation": "kılombiı", "turkish": "Kolombiya"},
    {"english": "Colombian", "pronunciation": "kılombiın", "turkish": "Kolombiyalı"},
    {"english": "Iran", "pronunciation": "iraan", "turkish": "İran"},
    {"english": "Iranian", "pronunciation": "ireyniın", "turkish": "İranlı"},
    {"english": "Ireland", "pronunciation": "ayılınd", "turkish": "İrlanda"},
    {"english": "Irish", "pronunciation": "ayriş", "turkish": "İrlandalı; İrlandaca"},
    {"english": "Italian", "pronunciation": "itelyın", "turkish": "İtalyan; İtalyanca"},
    {"english": "Italy", "pronunciation": "itıli", "turkish": "İtalya"},
    {"english": "Mexican", "pronunciation": "meksikın", "turkish": "Meksikalı"},
    {"english": "Mexico", "pronunciation": "meksikou", "turkish": "Meksika"},
    {"english": "New Zealand", "pronunciation": "nyuu ziilınd", "turkish": "Yeni Zelanda"},
    {"english": "New Zealander", "pronunciation": "nyuu ziilındı", "turkish": "Yeni Zelandalı"},
    {"english": "Nigeria", "pronunciation": "nayciriı", "turkish": "Nijerya"},
    {"english": "Nigerian", "pronunciation": "nayciriın", "turkish": "Nijeryalı"},
    {"english": "Pakistan", "pronunciation": "paakistaan", "turkish": "Pakistan"},
    {"english": "Pakistani", "pronunciation": "paakistaani", "turkish": "Pakistanlı"},
    {"english": "Poland", "pronunciation": "poulınd", "turkish": "Polonya"},
    {"english": "Polish", "pronunciation": "pouliş", "turkish": "Polonyalı; Lehçe"},
    {"english": "Russia", "pronunciation": "raşı", "turkish": "Rusya"},
    {"english": "Russian", "pronunciation": "raşın", "turkish": "Rus; Rusça"},
    {"english": "Saudi Arabia", "pronunciation": "saudi ıreybiı", "turkish": "Suudi Arabistan"},
    {"english": "Saudi Arabian", "pronunciation": "saudi ıreybiın", "turkish": "Suudi Arabistanlı"},
    {"english": "South Africa", "pronunciation": "saut efrikı", "turkish": "Güney Afrika"},
    {"english": "South African", "pronunciation": "saut efrikın", "turkish": "Güney Afrikalı"},
    {"english": "Thai", "pronunciation": "tay", "turkish": "Taylandlı; Tayca"},
    {"english": "Thailand", "pronunciation": "taylend", "turkish": "Tayland"},
    {"english": "Turkey", "pronunciation": "törki", "turkish": "Türkiye"},
    {"english": "Turkish", "pronunciation": "törkiş", "turkish": "Türk; Türkçe"},
    {"english": "UK", "pronunciation": "yuu key", "turkish": "Birleşik Krallık"},
    {"english": "USA", "pronunciation": "yuu es ey", "turkish": "Amerika Birleşik Devletleri"},
  ] },
  { id: "a1-introductions", title: "A1 • Tanışma ve Tanımlamalar", accent: "blue", words: [
    {"english": "brilliant", "pronunciation": "brilyınt", "turkish": "Harika, mükemmel"},
    {"english": "cool", "pronunciation": "kuul", "turkish": "Havalı, güzel"},
    {"english": "fantastic", "pronunciation": "fentestik", "turkish": "Harika"},
    {"english": "friendly", "pronunciation": "frendli", "turkish": "Arkadaş canlısı"},
    {"english": "great", "pronunciation": "greyt", "turkish": "Harika"},
    {"english": "kind", "pronunciation": "kaynd", "turkish": "Nazik, iyi kalpli"},
    {"english": "lovely", "pronunciation": "lavli", "turkish": "Hoş, sevimli"},
    {"english": "pleasant", "pronunciation": "plezınt", "turkish": "Hoş, cana yakın"},
    {"english": "popular", "pronunciation": "popyulı", "turkish": "Popüler, sevilen"},
    {"english": "quiet", "pronunciation": "kuayıt", "turkish": "Sessiz"},
    {"english": "warm", "pronunciation": "voom", "turkish": "Sıcak; samimi"},
    {"english": "well-known", "pronunciation": "vel noun", "turkish": "Tanınmış"},
    {"english": "visitor", "pronunciation": "vizitı", "turkish": "Ziyaretçi"},
    {"english": "April", "pronunciation": "eyprıl", "turkish": "Nisan"},
    {"english": "aunt", "pronunciation": "aant", "turkish": "Teyze, hala"},
    {"english": "amazing", "pronunciation": "ımeyzing", "turkish": "Muhteşem, şaşırtıcı"},
    {"english": "horrible", "pronunciation": "horıbıl", "turkish": "Berbat, korkunç"},
    {"english": "modern", "pronunciation": "modın", "turkish": "Modern"},
    {"english": "old", "pronunciation": "ould", "turkish": "Eski, yaşlı"},
    {"english": "poor", "pronunciation": "poo", "turkish": "Fakir"},
    {"english": "rich", "pronunciation": "riç", "turkish": "Zengin"},
    {"english": "terrible", "pronunciation": "terıbıl", "turkish": "Berbat"},
    {"english": "wonderful", "pronunciation": "vandıfıl", "turkish": "Harika"},
    {"english": "country", "pronunciation": "kantri", "turkish": "Ülke"},
    {"english": "education", "pronunciation": "ecyukeyşın", "turkish": "Eğitim"},
    {"english": "food", "pronunciation": "fuud", "turkish": "Yiyecek, yemek"},
    {"english": "lawyer", "pronunciation": "loyı", "turkish": "Avukat"},
    {"english": "parents", "pronunciation": "perınts", "turkish": "Anne ve baba, ebeveynler"},
    {"english": "university", "pronunciation": "yuunivörsıti", "turkish": "Üniversite"},
    {"english": "women", "pronunciation": "vimin", "turkish": "Kadınlar"},
    {"english": "interesting", "pronunciation": "intrısting", "turkish": "İlginç"},
    {"english": "happy", "pronunciation": "hepi", "turkish": "Mutlu"},
    {"english": "unfriendly", "pronunciation": "anfrendli", "turkish": "Arkadaş canlısı olmayan"},
    {"english": "unkind", "pronunciation": "ankaynd", "turkish": "Kaba, düşüncesiz"},
    {"english": "boring", "pronunciation": "boring", "turkish": "Sıkıcı"},
    {"english": "sad", "pronunciation": "sed", "turkish": "Üzgün"},
    {"english": "face", "pronunciation": "feys", "turkish": "Yüz"},
    {"english": "eyes", "pronunciation": "ayz", "turkish": "Gözler"},
    {"english": "body", "pronunciation": "bodi", "turkish": "Vücut"},
    {"english": "hands", "pronunciation": "hendz", "turkish": "Eller"},
    {"english": "arms", "pronunciation": "aamz", "turkish": "Kollar"},
    {"english": "feet", "pronunciation": "fiit", "turkish": "Ayaklar"},
    {"english": "first impression", "pronunciation": "först impreşın", "turkish": "İlk izlenim"},
    {"english": "opinion", "pronunciation": "ıpinyın", "turkish": "Görüş, fikir"},
    {"english": "body language", "pronunciation": "bodi lengvic", "turkish": "Beden dili"},
  ] },
  { id: "a1-school", title: "A1 • İş, Okul ve Saatler", accent: "green", words: [
    {"english": "personality", "pronunciation": "pörsınelıti", "turkish": "Kişilik"},
    {"english": "cleaner", "pronunciation": "kliinı", "turkish": "Temizlik görevlisi"},
    {"english": "dentist", "pronunciation": "dentist", "turkish": "Diş hekimi"},
    {"english": "engineer", "pronunciation": "encıniı", "turkish": "Mühendis"},
    {"english": "nurse", "pronunciation": "nöös", "turkish": "Hemşire"},
    {"english": "photographer", "pronunciation": "fıtogrıfı", "turkish": "Fotoğrafçı"},
    {"english": "pilot", "pronunciation": "paylıt", "turkish": "Pilot"},
    {"english": "police officer", "pronunciation": "pıliis ofisı", "turkish": "Polis memuru"},
    {"english": "shop assistant", "pronunciation": "şop ısistınt", "turkish": "Mağaza görevlisi"},
    {"english": "taxi driver", "pronunciation": "teksi drayvı", "turkish": "Taksi şoförü"},
    {"english": "break", "pronunciation": "breyk", "turkish": "Mola"},
    {"english": "exam", "pronunciation": "igzem", "turkish": "Sınav"},
    {"english": "fail an exam", "pronunciation": "feyl ın igzem", "turkish": "Sınavdan kalmak"},
    {"english": "get a good/bad mark", "pronunciation": "get ı gud / bed maak", "turkish": "İyi/kötü not almak"},
    {"english": "mark", "pronunciation": "maak", "turkish": "Not, puan"},
    {"english": "notes", "pronunciation": "nouts", "turkish": "Notlar"},
    {"english": "pass an exam", "pronunciation": "paas ın igzem", "turkish": "Sınavı geçmek"},
    {"english": "studies", "pronunciation": "stadiz", "turkish": "Öğrenim, çalışmalar"},
    {"english": "take notes", "pronunciation": "teyk nouts", "turkish": "Not almak"},
    {"english": "term", "pronunciation": "tööm", "turkish": "Okul dönemi"},
    {"english": "test", "pronunciation": "test", "turkish": "Test, sınav"},
    {"english": "timetable", "pronunciation": "taymteybıl", "turkish": "Ders programı"},
    {"english": "(a) quarter to/past", "pronunciation": "ı kuootı tu / paast", "turkish": "Çeyrek kala / çeyrek geçe"},
    {"english": "half past", "pronunciation": "haaf paast", "turkish": "Buçuk"},
    {"english": "o'clock", "pronunciation": "ıklok", "turkish": "Saat tam ..."},
    {"english": "past", "pronunciation": "paast", "turkish": "Saat söylerken: geçe"},
    {"english": "to", "pronunciation": "tu", "turkish": "Saat söylerken: kala"},
    {"english": "actor", "pronunciation": "ektı", "turkish": "Oyuncu"},
    {"english": "businessman", "pronunciation": "biznısmın", "turkish": "İş adamı"},
    {"english": "businesswoman", "pronunciation": "biznısvumın", "turkish": "İş kadını"},
    {"english": "chef", "pronunciation": "şef", "turkish": "Aşçı, şef"},
    {"english": "farmer", "pronunciation": "faamı", "turkish": "Çiftçi"},
    {"english": "manager", "pronunciation": "menicı", "turkish": "Yönetici"},
    {"english": "mechanic", "pronunciation": "mıkenik", "turkish": "Tamirci"},
    {"english": "receptionist", "pronunciation": "risepşınıst", "turkish": "Resepsiyon görevlisi"},
    {"english": "secretary", "pronunciation": "sekrıtri", "turkish": "Sekreter"},
    {"english": "tour guide", "pronunciation": "tuı gayd", "turkish": "Tur rehberi"},
  ] },
  { id: "a1-daily", title: "A1 • Hayvanlar, Teknoloji ve Günlük Yaşam", accent: "violet", words: [
    {"english": "tiger", "pronunciation": "taygı", "turkish": "Kaplan"},
    {"english": "squirrel", "pronunciation": "skvirıl", "turkish": "Sincap"},
    {"english": "monkey", "pronunciation": "manki", "turkish": "Maymun"},
    {"english": "penguin", "pronunciation": "pengvin", "turkish": "Penguen"},
    {"english": "camel", "pronunciation": "kemıl", "turkish": "Deve"},
    {"english": "meerkat", "pronunciation": "miıket", "turkish": "Mirket"},
    {"english": "praying mantis", "pronunciation": "preying mentis", "turkish": "Peygamberdevesi"},
    {"english": "jellyfish", "pronunciation": "celifiş", "turkish": "Denizanası"},
    {"english": "spider", "pronunciation": "spaydı", "turkish": "Örümcek"},
    {"english": "frog", "pronunciation": "frog", "turkish": "Kurbağa"},
    {"english": "goat", "pronunciation": "gout", "turkish": "Keçi"},
    {"english": "giraffe", "pronunciation": "cıraaf", "turkish": "Zürafa"},
    {"english": "lion", "pronunciation": "layın", "turkish": "Aslan"},
    {"english": "zebra", "pronunciation": "zebrı", "turkish": "Zebra"},
    {"english": "bear", "pronunciation": "beı", "turkish": "Ayı"},
    {"english": "crocodile", "pronunciation": "krokıdayl", "turkish": "Timsah"},
    {"english": "elephant", "pronunciation": "elifınt", "turkish": "Fil"},
    {"english": "graph", "pronunciation": "graaf", "turkish": "Grafik"},
    {"english": "table", "pronunciation": "teybıl", "turkish": "Tablo; masa"},
    {"english": "video", "pronunciation": "vidiou", "turkish": "Video"},
    {"english": "podcast", "pronunciation": "podkaast", "turkish": "Sesli yayın"},
    {"english": "online", "pronunciation": "onlayn", "turkish": "Çevrim içi"},
    {"english": "lecture", "pronunciation": "lekçı", "turkish": "Ders, konferans"},
    {"english": "(three) times a", "pronunciation": "trii taymz ı", "turkish": "... başına üç kez"},
    {"english": "every day", "pronunciation": "evri dey", "turkish": "Her gün"},
    {"english": "often", "pronunciation": "ofın", "turkish": "Sık sık"},
    {"english": "once a week", "pronunciation": "vans ı viik", "turkish": "Haftada bir kez"},
    {"english": "twice a week", "pronunciation": "tvays ı viik", "turkish": "Haftada iki kez"},
    {"english": "camera", "pronunciation": "kemrı", "turkish": "Kamera, fotoğraf makinesi"},
    {"english": "computer", "pronunciation": "kımpyuutı", "turkish": "Bilgisayar"},
    {"english": "headphones", "pronunciation": "hedfounz", "turkish": "Kulaklık"},
    {"english": "keyboard", "pronunciation": "kiibood", "turkish": "Klavye"},
    {"english": "laptop", "pronunciation": "leptop", "turkish": "Dizüstü bilgisayar"},
    {"english": "printer", "pronunciation": "printı", "turkish": "Yazıcı"},
    {"english": "smartphone", "pronunciation": "smaatfoun", "turkish": "Akıllı telefon"},
    {"english": "smartwatch", "pronunciation": "smaatvoç", "turkish": "Akıllı saat"},
    {"english": "speaker", "pronunciation": "spiikı", "turkish": "Hoparlör"},
    {"english": "tablet", "pronunciation": "teblıt", "turkish": "Tablet"},
    {"english": "satnav", "pronunciation": "setnev", "turkish": "Navigasyon cihazı"},
    {"english": "buy", "pronunciation": "bay", "turkish": "Satın almak"},
    {"english": "cost", "pronunciation": "kost", "turkish": "Fiyatı olmak; tutmak; tuttu"},
    {"english": "decide", "pronunciation": "disayd", "turkish": "Karar vermek"},
    {"english": "find", "pronunciation": "faynd", "turkish": "Bulmak"},
    {"english": "help", "pronunciation": "help", "turkish": "Yardım etmek"},
    {"english": "meet", "pronunciation": "miit", "turkish": "Tanışmak, buluşmak"},
    {"english": "prefer", "pronunciation": "priföö", "turkish": "Tercih etmek"},
    {"english": "sell", "pronunciation": "sel", "turkish": "Satmak"},
    {"english": "stay", "pronunciation": "stey", "turkish": "Kalmak"},
    {"english": "try", "pronunciation": "tray", "turkish": "Denemek"},
  ] },
  { id: "a1-life", title: "A1 • Doğa ve Yaşam", accent: "blue", words: [
    {"english": "eagle", "pronunciation": "iigıl", "turkish": "Kartal"},
    {"english": "fox", "pronunciation": "foks", "turkish": "Tilki"},
    {"english": "fur coat", "pronunciation": "föö kout", "turkish": "Kürk manto"},
    {"english": "hare", "pronunciation": "heı", "turkish": "Yaban tavşanı"},
    {"english": "hunter", "pronunciation": "hantı", "turkish": "Avcı"},
    {"english": "sheep", "pronunciation": "şiip", "turkish": "Koyun"},
    {"english": "tent", "pronunciation": "tent", "turkish": "Çadır"},
    {"english": "wolf", "pronunciation": "vulf", "turkish": "Kurt"},
    {"english": "catch", "pronunciation": "keç", "turkish": "Yakalamak"},
    {"english": "keep", "pronunciation": "kiip", "turkish": "Tutmak, saklamak"},
    {"english": "move", "pronunciation": "muuv", "turkish": "Hareket etmek, taşınmak"},
    {"english": "ride", "pronunciation": "rayd", "turkish": "Binmek, sürmek"},
    {"english": "live", "pronunciation": "liv", "turkish": "Yaşamak"},
    {"english": "use", "pronunciation": "yuuz", "turkish": "Kullanmak"},
    {"english": "full-time study", "pronunciation": "ful taym stadi", "turkish": "Tam zamanlı öğrenim"},
    {"english": "daily life", "pronunciation": "deyli layf", "turkish": "Günlük yaşam"},
    {"english": "heart disease", "pronunciation": "haat diziiz", "turkish": "Kalp hastalığı"},
    {"english": "mental health", "pronunciation": "mentıl helt", "turkish": "Ruh sağlığı"},
  ] },
  { id: "a1-food", title: "A1 • Yiyecek ve Restoran", accent: "green", words: [
    {"english": "bean", "pronunciation": "biin", "turkish": "Fasulye"},
    {"english": "carrot", "pronunciation": "kerıt", "turkish": "Havuç"},
    {"english": "chicken", "pronunciation": "çikın", "turkish": "Tavuk"},
    {"english": "grape", "pronunciation": "greyp", "turkish": "Üzüm"},
    {"english": "lamb", "pronunciation": "lem", "turkish": "Kuzu; kuzu eti"},
    {"english": "lemon", "pronunciation": "lemın", "turkish": "Limon"},
    {"english": "mushroom", "pronunciation": "maşruum", "turkish": "Mantar"},
    {"english": "onion", "pronunciation": "anyın", "turkish": "Soğan"},
    {"english": "pear", "pronunciation": "peı", "turkish": "Armut"},
    {"english": "steak", "pronunciation": "steyk", "turkish": "Biftek"},
    {"english": "bag", "pronunciation": "beg", "turkish": "Poşet, çanta"},
    {"english": "bake", "pronunciation": "beyk", "turkish": "Fırında pişirmek"},
    {"english": "boil", "pronunciation": "boyl", "turkish": "Kaynatmak, haşlamak"},
    {"english": "boiled", "pronunciation": "boyld", "turkish": "Haşlanmış"},
    {"english": "fried", "pronunciation": "frayd", "turkish": "Kızartılmış"},
    {"english": "fry", "pronunciation": "fray", "turkish": "Kızartmak"},
    {"english": "grill", "pronunciation": "gril", "turkish": "Izgarada pişirmek"},
    {"english": "grilled", "pronunciation": "grild", "turkish": "Izgarada pişmiş"},
    {"english": "roast", "pronunciation": "roust", "turkish": "Fırında kızartmak; kızarmış"},
    {"english": "restaurant", "pronunciation": "restront", "turkish": "Restoran"},
    {"english": "waiter", "pronunciation": "veytı", "turkish": "Garson"},
    {"english": "main course", "pronunciation": "meyn koos", "turkish": "Ana yemek"},
    {"english": "order", "pronunciation": "oodı", "turkish": "Sipariş; sipariş vermek"},
    {"english": "starter", "pronunciation": "staatı", "turkish": "Başlangıç yemeği"},
    {"english": "back", "pronunciation": "bek", "turkish": "Arka; geri"},
    {"english": "bar", "pronunciation": "baa", "turkish": "Bar; kalıp yiyecek"},
    {"english": "bottle", "pronunciation": "botıl", "turkish": "Şişe"},
    {"english": "burger", "pronunciation": "böögı", "turkish": "Hamburger"},
    {"english": "can", "pronunciation": "ken", "turkish": "İçecek kutusu"},
    {"english": "cereal", "pronunciation": "siıriıl", "turkish": "Kahvaltılık gevrek"},
    {"english": "cola", "pronunciation": "koulı", "turkish": "Kola"},
    {"english": "crisps", "pronunciation": "krisps", "turkish": "Patates cipsi"},
    {"english": "curry", "pronunciation": "kari", "turkish": "Köri; körili yemek"},
    {"english": "garlic", "pronunciation": "gaalik", "turkish": "Sarımsak"},
    {"english": "jam", "pronunciation": "cem", "turkish": "Reçel"},
    {"english": "jar", "pronunciation": "caa", "turkish": "Kavanoz"},
    {"english": "melon", "pronunciation": "melın", "turkish": "Kavun"},
    {"english": "packet", "pronunciation": "pekıt", "turkish": "Paket"},
    {"english": "salad", "pronunciation": "selıd", "turkish": "Salata"},
    {"english": "tin", "pronunciation": "tin", "turkish": "Konserve kutusu"},
    {"english": "yoghurt", "pronunciation": "yogıt", "turkish": "Yoğurt"},
    {"english": "restaurant food", "pronunciation": "restront fuud", "turkish": "Restoran yemeği"},
    {"english": "street food", "pronunciation": "striit fuud", "turkish": "Sokak yemeği"},
    {"english": "hot", "pronunciation": "hot", "turkish": "Sıcak; acı"},
    {"english": "spicy", "pronunciation": "spaysi", "turkish": "Baharatlı, acı"},
    {"english": "fast", "pronunciation": "faast", "turkish": "Hızlı"},
    {"english": "delicious", "pronunciation": "dilişıs", "turkish": "Lezzetli"},
    {"english": "exciting", "pronunciation": "iksayting", "turkish": "Heyecan verici"},
    {"english": "cheese", "pronunciation": "çiiz", "turkish": "Peynir"},
    {"english": "egg", "pronunciation": "eg", "turkish": "Yumurta"},
    {"english": "fish", "pronunciation": "fiş", "turkish": "Balık"},
    {"english": "juice", "pronunciation": "cuus", "turkish": "Meyve suyu"},
    {"english": "grapes", "pronunciation": "greyps", "turkish": "Üzümler"},
    {"english": "seeds", "pronunciation": "siidz", "turkish": "Tohumlar, çekirdekler"},
    {"english": "nuts", "pronunciation": "nats", "turkish": "Kuruyemiş"},
    {"english": "honey", "pronunciation": "hani", "turkish": "Bal"},
    {"english": "vegetarian food", "pronunciation": "vecıteıriın fuud", "turkish": "Vejetaryen yemek"},
    {"english": "vegan food", "pronunciation": "viigın fuud", "turkish": "Vegan yemek"},
    {"english": "café", "pronunciation": "kefey", "turkish": "Kafe"},
  ] },
  { id: "a1-city", title: "A1 • Ev, Şehir ve Mekânlar", accent: "violet", words: [
    {"english": "building", "pronunciation": "bilding", "turkish": "Bina"},
    {"english": "outside", "pronunciation": "autsayd", "turkish": "Dışarıda, dışarısı"},
    {"english": "arm", "pronunciation": "aam", "turkish": "Kol"},
    {"english": "bedside table", "pronunciation": "bedsayd teybıl", "turkish": "Komodin"},
    {"english": "bookcase", "pronunciation": "bukkeys", "turkish": "Kitaplık"},
    {"english": "chest of drawers", "pronunciation": "çest ıv drooz", "turkish": "Şifonyer, çekmeceli dolap"},
    {"english": "cooker", "pronunciation": "kukı", "turkish": "Ocak, fırınlı ocak"},
    {"english": "curtains", "pronunciation": "köötınz", "turkish": "Perdeler"},
    {"english": "lamp", "pronunciation": "lemp", "turkish": "Lamba"},
    {"english": "mirror", "pronunciation": "mirı", "turkish": "Ayna"},
    {"english": "sink", "pronunciation": "sink", "turkish": "Lavabo, evye"},
    {"english": "sofa", "pronunciation": "soufı", "turkish": "Kanepe"},
    {"english": "wardrobe", "pronunciation": "voodroub", "turkish": "Gardırop"},
    {"english": "washing machine", "pronunciation": "voşing mışiin", "turkish": "Çamaşır makinesi"},
    {"english": "bridge", "pronunciation": "bric", "turkish": "Köprü"},
    {"english": "concert hall", "pronunciation": "konsıt hool", "turkish": "Konser salonu"},
    {"english": "park", "pronunciation": "paak", "turkish": "Park"},
    {"english": "police station", "pronunciation": "pıliis steyşın", "turkish": "Polis karakolu"},
    {"english": "post office", "pronunciation": "poust ofis", "turkish": "Postane"},
    {"english": "sports centre", "pronunciation": "spoorts sentı", "turkish": "Spor merkezi"},
    {"english": "stadium", "pronunciation": "steydiım", "turkish": "Stadyum"},
    {"english": "theatre", "pronunciation": "tiıtı", "turkish": "Tiyatro"},
    {"english": "capital", "pronunciation": "kepitıl", "turkish": "Başkent"},
    {"english": "countryside", "pronunciation": "kantrisayd", "turkish": "Kırsal bölge"},
    {"english": "expert", "pronunciation": "ekspööt", "turkish": "Uzman"},
    {"english": "opportunity", "pronunciation": "opıtyuunıti", "turkish": "Fırsat"},
    {"english": "population", "pronunciation": "popyuleyşın", "turkish": "Nüfus"},
    {"english": "traffic", "pronunciation": "trefik", "turkish": "Trafik"},
    {"english": "pollution", "pronunciation": "pıluuşın", "turkish": "Kirlilik"},
    {"english": "ancient", "pronunciation": "eynşınt", "turkish": "Antik, çok eski"},
    {"english": "apartment", "pronunciation": "ıpaatmınt", "turkish": "Daire"},
    {"english": "cave", "pronunciation": "keyv", "turkish": "Mağara"},
    {"english": "recognize", "pronunciation": "rekıgnayz", "turkish": "Tanımak, fark etmek"},
    {"english": "rock", "pronunciation": "rok", "turkish": "Kaya"},
    {"english": "strange", "pronunciation": "streync", "turkish": "Garip"},
    {"english": "canal", "pronunciation": "kınel", "turkish": "Kanal"},
    {"english": "gondola", "pronunciation": "gondılı", "turkish": "Gondol"},
    {"english": "man-made", "pronunciation": "men meyd", "turkish": "İnsan yapımı"},
    {"english": "palace", "pronunciation": "pelıs", "turkish": "Saray"},
    {"english": "stilts", "pronunciation": "stilts", "turkish": "Uzun destek direkleri"},
    {"english": "along", "pronunciation": "ılong", "turkish": "Boyunca"},
    {"english": "directions", "pronunciation": "direkşınz", "turkish": "Yol tarifi"},
    {"english": "left", "pronunciation": "left", "turkish": "Sol"},
    {"english": "metro station", "pronunciation": "metrou steyşın", "turkish": "Metro istasyonu"},
    {"english": "right", "pronunciation": "rayt", "turkish": "Sağ"},
    {"english": "centre", "pronunciation": "sentı", "turkish": "Merkez"},
    {"english": "flats", "pronunciation": "flets", "turkish": "Daireler"},
    {"english": "square", "pronunciation": "skveı", "turkish": "Meydan; kare"},
    {"english": "hotel", "pronunciation": "houtel", "turkish": "Otel"},
    {"english": "hostel", "pronunciation": "hostıl", "turkish": "Hostel, ekonomik konaklama yeri"},
    {"english": "camping ground", "pronunciation": "kemping graund", "turkish": "Kamp alanı"},
    {"english": "brick", "pronunciation": "brik", "turkish": "Tuğla"},
    {"english": "wood", "pronunciation": "vud", "turkish": "Ahşap, odun"},
    {"english": "mud", "pronunciation": "mad", "turkish": "Çamur"},
    {"english": "private", "pronunciation": "prayvıt", "turkish": "Özel"},
    {"english": "environment", "pronunciation": "invayrınmınt", "turkish": "Çevre"},
    {"english": "eco-friendly", "pronunciation": "iikou frendli", "turkish": "Çevre dostu"},
    {"english": "roof", "pronunciation": "ruuf", "turkish": "Çatı"},
    {"english": "area", "pronunciation": "eıriı", "turkish": "Alan, bölge"},
    {"english": "cheap", "pronunciation": "çiip", "turkish": "Ucuz"},
    {"english": "downtown", "pronunciation": "dauntaun", "turkish": "Şehir merkezi"},
    {"english": "expensive", "pronunciation": "ikspensiv", "turkish": "Pahalı"},
    {"english": "local", "pronunciation": "loukıl", "turkish": "Yerel"},
    {"english": "noisy", "pronunciation": "noyzi", "turkish": "Gürültülü"},
    {"english": "field", "pronunciation": "fiild", "turkish": "Tarla, açık alan"},
    {"english": "lake", "pronunciation": "leyk", "turkish": "Göl"},
    {"english": "located", "pronunciation": "loukeytıd", "turkish": "Bulunan, konumlanmış"},
    {"english": "urban", "pronunciation": "ööbın", "turkish": "Kentsel"},
  ] },
  { id: "a1-family", title: "A1 • Aile, Tarih ve Kültür", accent: "blue", words: [
    {"english": "woods", "pronunciation": "vudz", "turkish": "Ormanlık alan"},
    {"english": "August", "pronunciation": "oogıst", "turkish": "Ağustos"},
    {"english": "brother", "pronunciation": "bradır", "turkish": "Erkek kardeş"},
    {"english": "cousin", "pronunciation": "kazın", "turkish": "Kuzen"},
    {"english": "grandchildren", "pronunciation": "grençildrın", "turkish": "Torunlar"},
    {"english": "granddaughter", "pronunciation": "grendootı", "turkish": "Kız torun"},
    {"english": "grandfather", "pronunciation": "grenfaadır", "turkish": "Dede"},
    {"english": "grandmother", "pronunciation": "grenmaadır", "turkish": "Büyükanne"},
    {"english": "grandparents", "pronunciation": "grenperınts", "turkish": "Büyükanne ve büyükbaba"},
    {"english": "grandson", "pronunciation": "grensan", "turkish": "Erkek torun"},
    {"english": "sister", "pronunciation": "sistı", "turkish": "Kız kardeş"},
    {"english": "uncle", "pronunciation": "ankıl", "turkish": "Amca, dayı"},
    {"english": "armchair", "pronunciation": "aamçeı", "turkish": "Koltuk"},
    {"english": "bought", "pronunciation": "boot", "turkish": "Satın aldı"},
    {"english": "came", "pronunciation": "keym", "turkish": "Geldi"},
    {"english": "got", "pronunciation": "got", "turkish": "Aldı, elde etti"},
    {"english": "made", "pronunciation": "meyd", "turkish": "Yaptı, üretti"},
    {"english": "spent", "pronunciation": "spent", "turkish": "Harcadı; zaman geçirdi"},
    {"english": "told", "pronunciation": "tould", "turkish": "Söyledi, anlattı"},
    {"english": "went", "pronunciation": "vent", "turkish": "Gitti"},
    {"english": "attractive", "pronunciation": "ıtrektiv", "turkish": "Çekici"},
    {"english": "became", "pronunciation": "bikeym", "turkish": "Oldu, hâline geldi"},
    {"english": "cut", "pronunciation": "kat", "turkish": "Kesmek; kesti"},
    {"english": "December", "pronunciation": "disembı", "turkish": "Aralık"},
    {"english": "did", "pronunciation": "did", "turkish": "Yaptı"},
    {"english": "February", "pronunciation": "februıri", "turkish": "Şubat"},
    {"english": "found out", "pronunciation": "faund aut", "turkish": "Öğrendi, keşfetti"},
    {"english": "gave", "pronunciation": "geyv", "turkish": "Verdi"},
    {"english": "in (1962,etc)", "pronunciation": "in", "turkish": "Yıllarla: ... yılında"},
    {"english": "January", "pronunciation": "cenyuri", "turkish": "Ocak"},
    {"english": "July", "pronunciation": "culay", "turkish": "Temmuz"},
    {"english": "June", "pronunciation": "cuun", "turkish": "Haziran"},
    {"english": "lost", "pronunciation": "lost", "turkish": "Kaybetti"},
    {"english": "March", "pronunciation": "maaç", "turkish": "Mart"},
    {"english": "May", "pronunciation": "mey", "turkish": "Mayıs"},
    {"english": "November", "pronunciation": "nouvembı", "turkish": "Kasım"},
    {"english": "October", "pronunciation": "oktoubı", "turkish": "Ekim"},
    {"english": "on (June 19th, etc)", "pronunciation": "on", "turkish": "Tarihlerle: ... tarihinde"},
    {"english": "September", "pronunciation": "septembı", "turkish": "Eylül"},
    {"english": "sold", "pronunciation": "sould", "turkish": "Sattı"},
    {"english": "thought", "pronunciation": "toot", "turkish": "Düşündü"},
    {"english": "won", "pronunciation": "van", "turkish": "Kazandı"},
    {"english": "brought", "pronunciation": "broot", "turkish": "Getirdi"},
    {"english": "DNA testing", "pronunciation": "dii en ey testing", "turkish": "DNA testi"},
    {"english": "library", "pronunciation": "laybrıri", "turkish": "Kütüphane"},
    {"english": "family tree", "pronunciation": "femıli trii", "turkish": "Soy ağacı"},
    {"english": "website", "pronunciation": "vebsayt", "turkish": "İnternet sitesi"},
    {"english": "luck", "pronunciation": "lak", "turkish": "Şans"},
    {"english": "adopted", "pronunciation": "ıdoptıd", "turkish": "Evlat edinilmiş"},
    {"english": "separate", "pronunciation": "sepıreyt", "turkish": "Ayırmak"},
    {"english": "long-lost", "pronunciation": "long lost", "turkish": "Uzun zamandır kayıp/görüşülmeyen"},
    {"english": "get married", "pronunciation": "get merid", "turkish": "Evlenmek"},
    {"english": "then", "pronunciation": "den", "turkish": "Sonra, o zaman"},
    {"english": "after", "pronunciation": "aaftı", "turkish": "Sonra"},
    {"english": "between… and….", "pronunciation": "bitviin ... end ...", "turkish": "... ile ... arasında"},
    {"english": "later", "pronunciation": "leytı", "turkish": "Daha sonra"},
    {"english": "ago", "pronunciation": "ıgou", "turkish": "Önce"},
    {"english": "in", "pronunciation": "in", "turkish": "İçinde; -de/-da"},
    {"english": "celebrate", "pronunciation": "selıbreyt", "turkish": "Kutlamak"},
    {"english": "culture", "pronunciation": "kalçı", "turkish": "Kültür"},
    {"english": "gift", "pronunciation": "gift", "turkish": "Hediye"},
    {"english": "the ground", "pronunciation": "dı graund", "turkish": "Yer, zemin"},
    {"english": "lucky", "pronunciation": "laki", "turkish": "Şanslı"},
    {"english": "traditional", "pronunciation": "trıdişınıl", "turkish": "Geleneksel"},
    {"english": "activity", "pronunciation": "ektivıti", "turkish": "Etkinlik, faaliyet"},
    {"english": "highlight", "pronunciation": "haylayt", "turkish": "En dikkat çekici bölüm"},
  ] },
  { id: "a1-travel", title: "A1 • Seyahat ve Ulaşım", accent: "green", words: [
    {"english": "history", "pronunciation": "histri", "turkish": "Tarih"},
    {"english": "take part in", "pronunciation": "teyk paat in", "turkish": "Katılmak"},
    {"english": "band", "pronunciation": "bend", "turkish": "Müzik grubu"},
    {"english": "enjoy", "pronunciation": "incoy", "turkish": "Keyif almak"},
    {"english": "entertainment", "pronunciation": "entıteynmınt", "turkish": "Eğlence"},
    {"english": "bitter", "pronunciation": "bitı", "turkish": "Acı; keskin soğuk"},
    {"english": "certain", "pronunciation": "söötın", "turkish": "Kesin, emin; belirli"},
    {"english": "melt", "pronunciation": "melt", "turkish": "Erimek"},
    {"english": "spectacle", "pronunciation": "spektıkıl", "turkish": "Görkemli gösteri/manzara"},
    {"english": "thaw", "pronunciation": "too", "turkish": "Buzların çözülmesi"},
    {"english": "aeroplane", "pronunciation": "eırıpleyn", "turkish": "Uçak"},
    {"english": "bus", "pronunciation": "bas", "turkish": "Otobüs"},
    {"english": "coach", "pronunciation": "kouç", "turkish": "Şehirler arası/tur otobüsü"},
    {"english": "cruise ship", "pronunciation": "kruuz şip", "turkish": "Gezi gemisi"},
    {"english": "ferry", "pronunciation": "feri", "turkish": "Feribot, vapur"},
    {"english": "helicopter", "pronunciation": "helikoptı", "turkish": "Helikopter"},
    {"english": "plane", "pronunciation": "pleyn", "turkish": "Uçak"},
    {"english": "scooter", "pronunciation": "skuutı", "turkish": "Skuter, küçük motosiklet"},
    {"english": "ship", "pronunciation": "şip", "turkish": "Gemi"},
    {"english": "speedboat", "pronunciation": "spiidbout", "turkish": "Sürat teknesi"},
    {"english": "train", "pronunciation": "treyn", "turkish": "Tren"},
    {"english": "tram", "pronunciation": "trem", "turkish": "Tramvay"},
    {"english": "clean", "pronunciation": "kliin", "turkish": "Temiz"},
    {"english": "comfortable", "pronunciation": "kamftıbıl", "turkish": "Rahat"},
    {"english": "crowded", "pronunciation": "kraudıd", "turkish": "Kalabalık"},
    {"english": "dangerous", "pronunciation": "deyncırıs", "turkish": "Tehlikeli"},
    {"english": "dirty", "pronunciation": "dööti", "turkish": "Kirli"},
    {"english": "empty", "pronunciation": "empti", "turkish": "Boş"},
    {"english": "full", "pronunciation": "ful", "turkish": "Dolu"},
    {"english": "safe", "pronunciation": "seyf", "turkish": "Güvenli"},
    {"english": "slow", "pronunciation": "slou", "turkish": "Yavaş"},
    {"english": "uncomfortable", "pronunciation": "ankamftıbıl", "turkish": "Rahat olmayan"},
    {"english": "catch a train", "pronunciation": "keç ı treyn", "turkish": "Trene yetişmek/binmek"},
    {"english": "change trains", "pronunciation": "çeync treynz", "turkish": "Tren değiştirmek, aktarma yapmak"},
    {"english": "get off (a bus etc)", "pronunciation": "get of", "turkish": "Araçtan inmek"},
    {"english": "get on (a train etc)", "pronunciation": "get on", "turkish": "Araca binmek"},
    {"english": "miss (a plane etc)", "pronunciation": "mis", "turkish": "Aracı kaçırmak"},
    {"english": "take (a train etc)", "pronunciation": "teyk", "turkish": "Ulaşım aracını kullanmak"},
    {"english": "excuse me", "pronunciation": "ikskyuuz mii", "turkish": "Affedersiniz"},
    {"english": "I'm sorry", "pronunciation": "aym sori", "turkish": "Özür dilerim, üzgünüm"},
    {"english": "road trip", "pronunciation": "roud trip", "turkish": "Karayolu gezisi"},
    {"english": "magnificent", "pronunciation": "megnifisınt", "turkish": "Muhteşem, görkemli"},
    {"english": "world-famous", "pronunciation": "vööld feymıs", "turkish": "Dünyaca ünlü"},
    {"english": "produce", "pronunciation": "prıdyuus", "turkish": "Üretmek"},
    {"english": "passenger", "pronunciation": "pesıncı", "turkish": "Yolcu"},
    {"english": "vehicle", "pronunciation": "viıkıl", "turkish": "Araç"},
    {"english": "electric", "pronunciation": "ilektrik", "turkish": "Elektrikli"},
    {"english": "charge", "pronunciation": "çaac", "turkish": "Şarj etmek"},
    {"english": "battery", "pronunciation": "betıri", "turkish": "Pil, batarya"},
    {"english": "metal", "pronunciation": "metıl", "turkish": "Metal"},
  ] },
]
